title: Wei Wang
logo: /img/logo.jpg
description: PhD candidate in Computer Vision Lab, Informatics Institute, University of Amsterdam 
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal

