title: Wei Wang
logo: /img/logo.jpg
description: PhD candidate in Computer Vision Lab, Informatics Institute, University of Amsterdam <a href="https://ivi.uva.nl/">Download <strong>ZIP File</strong></a>
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal

